#ifndef __OALINTR_H
#define __OALINTR_H

#ifndef __SYSINTR_H
#include <sysintr.h>
#endif
	

#define SYSINTR_KEYBOARD    			(SYSINTR_FIRMWARE+0)
#define ISR_KEYBOARD SYSINTR_KEYBOARD

#define SYSINTR_TOUCH       			(SYSINTR_FIRMWARE+1)
#define ISR_TOUCH SYSINTR_TOUCH

#define SYSINTR_POWER         			(SYSINTR_FIRMWARE+2)

#define SYSINTR_SERIAL      			(SYSINTR_FIRMWARE+3)
#define ISR_SERIAL SYSINTR_SERIAL

#define SYSINTR_AUDIO       			(SYSINTR_FIRMWARE+4)

#define SYSINTR_PCMCIA_STATE    		(SYSINTR_FIRMWARE+5)
#define ISR_PCMCIA_STATE SYSINTR_PCMCIA_STATE

#define SYSINTR_PCMCIA_EDGE     		(SYSINTR_FIRMWARE+6)

#define SYSINTR_PCMCIA_LEVEL    		(SYSINTR_FIRMWARE+7)
#define ISR_PCMCIA_LEVEL SYSINTR_PCMCIA_LEVEL

#define SYSINTR_TOUCH_CHANGED   		(SYSINTR_FIRMWARE+8)
#define SYSINTR_IR          			(SYSINTR_FIRMWARE+9)
#define SYSINTR_ETHER       			(SYSINTR_FIRMWARE+10)

#define SYSINTR_MOUSE       			(SYSINTR_FIRMWARE+11)
#define ISR_MOUSE SYSINTR_MOUSE

#define SYSINTR_SERIAL1					(SYSINTR_FIRMWARE+12)
#define SYSINTR_OHCI_MDD				(SYSINTR_FIRMWARE+13)
#define SYSINTR_OHCI_PDD				(SYSINTR_FIRMWARE+14)
#define SYSINTR_USB_CLIENT				(SYSINTR_FIRMWARE+15)

#define SYSINTR_GSM						(SYSINTR_FIRMWARE+16) //GSM key
#define SYSINTR_FUNKEY					(SYSINTR_FIRMWARE+17) //function key
#define SYSINTR_AC						(SYSINTR_FIRMWARE+18) 
#define SYSINTR_BATTERY					(SYSINTR_FIRMWARE+19) 

#define SYSINTR_TIMER3					(SYSINTR_FIRMWARE+20) //led
#define ISR_TIMER3 SYSINTR_TIMER3

#endif // __OALINTR_H



