//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by system.rc
//
#define OBM_CAPTION_OK                  101
#define OBM_CAPTION_CLOSE               102
#define OBM_CAPTION_HELP                103
#define IDB_KINGMOS                     104
#define IDI_SYSLOGO                     106
#define OBM_CAPTION_CLOSE_GRAY          107
#define OBM_CAPTION_HELP_GRAY           108
#define OBM_CAPTION_OK_GRAY             109
#define IDI_SYSLOGO_G                   110
#define IDI_FOLDER                      118
#define IDI_UNKNOWFILE                  119
#define IDI_BMPFILE                     120
#define IDI_TEXTFILE                    121
#define OBM_TOOL_DELETE_GRAY            126
#define OBM_TOOL_EMAIL                  127
#define IDB_TOOL_FIND                   129
#define OBM_TOOL_OPEN                   130
#define OBM_TOOL_UPFOLDER               131
#define OBM_TOOL_UPFOLDER_GRAY          132
#define OBM_TOOL_MESSAGE                134
#define OBM_TOOL_NEW                    135
#define OBM_TOOL_FAX                    136
#define OBM_TOOL_RENAME                 137
#define OBM_TOOL_RENAME_GRAY            138
#define OIC_TOOL_COPY                   139
#define OIC_TOOL_COPY_GRAY              140
#define OIC_TOOL_DELETE                 141
#define OIC_TOOL_DELETE_GRAY            142
#define OIC_TOOL_EMAIL                  143
#define OIC_TOOL_FAX                    144
#define OIC_TOOL_FIND                   145
#define OIC_TOOL_OPEN                   146
#define OIC_TOOL_UPFOLDER               147
#define OIC_TOOL_UPFOLDER_GRAY          148
#define OIC_TOOL_MESSAGE                149
#define OIC_TOOL_NEW                    150
#define OIC_TOOL_PASTE                  151
#define OIC_TOOL_PASTE_GRAY             152
#define OIC_TOOL_RENAME                 153
#define OIC_TOOL_RENAME_GRAY            154
#define OBM_TOOL_COPY                   155
#define OBM_TOOL_COPY_GRAY              156
#define OBM_TOOL_DELETE                 157
#define OBM_TOOL_FIND                   159
#define OBM_TOOL_PASTE                  160
#define OBM_TOOL_PASTE_GRAY             161
#define OBM_TOOL_PHONE                  173
#define IDI_CNTUNCHECK                  175
#define IDI_CNTCHECKED                  176
#define IDB_CNTDELETEENABLE             177
#define IDB_CNTADDENABLE                178
#define IDB_CNTDELETEDISABLE            179
#define IDB_CNTADDDISABLE               180
#define IDB_CNTEDITAREA                 181
#define IDB_CNTNOTEAREA                 183
#define IDB_CNTCATEGORYAREA             184
#define IDI_MP3FILE                     185
#define IDI_IEFILE                      186
#define IDI_EMAILFILE                   187
#define OIC_APP_ALARM                   188
#define OIC_APP_CALCULATOR              189
#define OIC_APP_CALENDAR                190
#define OIC_APP_CONTROL                 191
#define OIC_APP_DICTIONARY              192
#define OIC_APP_EASYBOX                 193
#define OIC_APP_FILEMANAGE              194
#define OIC_APP_INTERNET                195
#define OIC_APP_MP3                     196
#define OIC_APP_NAMECARD                197
#define OIC_APP_NOTEBOOK                198
#define OIC_APP_PHONE                   199
#define OIC_APP_PLANE                   200
#define OIC_APP_SYSTEM                  201
#define OIC_APPLICATION                 202
#define OIC_RUSSBLOCK                   203
#define OIC_SLIDERBLOCK_BOTTOM          204
#define OIC_SLIDERBLOCK_HORZBOTH        205
#define OIC_SLIDERBLOCK_TOP             206
#define IDI_EXEFILE                     208
#define IDI_GIFFILE                     209
#define IDI_DOWN                        210
#define IDI_DOWNDOWN                    211
#define IDI_DOWNGRAY                    212
#define OBM_VSCROLLBAR_UPARROW          230
#define OBM_VSCROLLBAR_DOWNARROW        231
#define OBM_VSCROLLBAR_THUMB            232
#define OBM_VSCROLLBAR_BACKGROUND       233
#define OBM_HSCROLLBAR_BACKGROUND       234
#define OBM_HSCROLLBAR_LEFTARROW        235
#define OBM_HSCROLLBAR_THUMB            236
#define OBM_HSCROLLBAR_RIGHTARROW       237
#define OBM_SCROLLBAR_CORNER            238
#define OBM_MSG_INFO                    240
#define OBM_MSG_WARN                    241
#define OBM_BACKGROUND                  242
#define OBM_VPROGRESS_THUMB             243
#define OBM_HPROGRESS_THUMB             244
#define OBM_BORDER_MB                   245
#define OBM_BORDER_RB                   246
#define OBM_BORDER_LB                   247
#define OBM_BORDER_R                    248
#define OBM_BORDER_L                    249
#define OBM_CAP_MT                      250
#define OBM_CAP_RT                      251
#define OBM_CAP_LT                      252
#define OBM_CAP_LT_NA                   253
#define OBM_BORDER_L_NA                 254
#define OBM_BORDER_RB_NA                255
#define OBM_BORDER_R_NA                 256
#define OBM_CAP_MT_NA                   257
#define OBM_CAP_RT_NA                   258
#define OBM_BORDER_LB_NA                259
#define OBM_BORDER_MB_NA                260

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        261
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
