/******************************************************
Copyright(c) 版权所有，1998-2003微逻辑。保留所有权利。
******************************************************/

#ifndef __EUGWME_H
#define __EUGWME_H

#ifdef __cplusplus
extern "C" {
#endif      // __cplusplus 

enum {
	WND_CREATEEX = 1,
	WND_ISWINDOW,
	WND_SHOWSCROLLBAR,
	WND_DEFPROC,
	WND_DESTROY,
	WND_ISCHILD,
    WND_GETPARENT,
    WND_SETPARENT,
	WND_ISVISIBLE,
	WND_SHOW,             //10
	WND_ENABLE,
	WND_ISENABLED,
	WND_SETTEXT,
	WND_GETTEXT,
	WND_GETTEXTLENGTH,
	WND_GETCLIENTRECT,
	WND_GETWINDOWRECT,
	WND_SETPOS,
	WND_MOVE,			
	WND_BRINGTOTOP,        //20
	WND_CALLPROC,
	WND_ADJUSTRECTEX,
	WND_FLASH,
	WND_CLOSE,
	WND_ISICONIC,
	WND_ISZOOMED,
	WND_GETLONG,
	WND_SETLONG,
	WND_GETDESKTOP,
	WND_FIND,            //30
	WND_UPDATE,
	WND_GETUPDATERECT,
	WND_GETUPDATERGN,
	WND_ENUM,
	WND_ENUMCHILD,
	WND_GETTOP,
	WND_GET,
	WND_GETNEXT,
	WND_CLIENTTOSCREEN,
	WND_SCREENTOCLIENT,       //40
	WND_MAPPOINTS,
	WND_FROMPOINT,
	WND_CHILDFROMPOINT,
	WND_GETFOREGROUND,
	WND_SETFOREGROUND,
	WND_SETACTIVE,
	WND_SETTIMER,
	WND_KILLTIMER,
	WND_SETSYSTIMER,
	WND_KILLSYSTIMER,        //50
	WND_GETACTIVE,
	WND_GETTOPLEVELPARENT,
	WND_SETFOCUS,
	WND_GETFOCUS,
	WND_SETCAPTURE,
	WND_RELEASECAPTURE,
	WND_GETCAPTURE,
	WND_BEGINPAINT,
	WND_ENDPAINT,
	WND_GETCLIENTDC,       //60
	WND_RELEASEDC,
	WND_GETWINDOWDC,
	WND_DRAWCAPTION,
	WND_SCROLL,
	WND_GETDCEX,
	WND_INVALIDATERECT,
	WND_INVALIDATERGN,
	WND_VALIDATERECT,
	WND_VALIDATERGN,
	WND_GETTHREADPROCESSID,    //70
	WND_ENABLESCROLLBAR,
	WND_GETSCROLLINFO,
	WND_SETSCROLLINFO,
	WND_GETCLASSNAME,
	WND_CLEAR,

	CLASS_REGISTER,           
	CLASS_GETINFO,
	CLASS_UNREGISTER,
	CLASS_GETLONG,
	CLASS_SETLONG,
	CLASS_CLEAR,

	DLG_CREATEINDIRECT,
	DLG_CREATEINDIRECTPARAM,
	DLG_BOXINDIRECT,
	DLG_BOXINDIRECTPARAM,
	DLG_END,
	DLG_GETCTRLID,
	DLG_GETITEM,
	DLG_GETITEMTEXT,
	DLG_SETITEMTEXT,
	DLG_GETITEMINT,
	DLG_SETITEMINT,
	DLG_SENDITEMMESSAGE,
	DLG_MESSAGEBOX,
//ex
	DLG_CREATEINDIRECT_EX,
	DLG_CREATEINDIRECTPARAM_EX,
	DLG_BOXINDIRECT_EX,
	DLG_BOXINDIRECTPARAM_EX,
//ex-end
    WND_SHOWDESKTOP,
	WND_SETRGN,
	WND_GETRGN
};

enum{			
	MSG_POST = 1,
	MSG_POSTTHREAD,
	MSG_GET,                       //  80
	MSG_PEEK,
	MSG_POSTQUIT,
	MSG_DISPATCH,
	MSG_TRANSLATE,
	MSG_SEND,
	MSG_WAIT,	
	MOUSE_EVENT,
	KEYBD_EVENT,
	MSG_WAITFORMULTIPLEOBJECTS,
	MSG_BEEP,
	MSG_GETKEYSTATE,
	MSG_SENDTIMEOUT
};

enum{
// sys
	SYS_CLOSEOBJECT = 1,
	SYS_GETMETRICS,
	SYS_SETMETRICS,
	SYS_GETCOLOR,
	SYS_SETCOLORS,
	SYS_GETCOLORBRUSH,//         90
	SYS_TOUCHCALIBRATE,
// caret
	CARET_CREATE,
	CARET_DESTROY,
	CARET_GETBLINKTIME,
	CARET_GETPOS,
	CARET_HIDE,
	CARET_SETBLINKTIME,
	CARET_SETPOS,
	CARET_SHOW,
// menu
	MENU_CREATE,
	MENU_CREATEPOPUP,
	MENU_DESTROY,
	MENU_REMOVE,
	MENU_DELETE,
	MENU_INSERT,
	MENU_INSERTITEM,
    MENU_ENABLEITEM,
	MENU_GETDEFAULTITEM,
	MENU_SETDEFAULTITEM,
	MENU_SETITEMINFO,
	MENU_GETITEMCOUNT,
	MENU_GETITEMID,
	MENU_GETITEMINFO,
	MENU_GETSUB,
	MENU_TRACKPOPUP,
//  code page
    CP_MULTIBYTETOWIDECHAR,
	CP_WIDECHARTOMULTIBYTE,
	SYS_SETCALIBRATE_WINDOW,
	SYS_SETCALIBRATE_POINTS,
};

enum{			
	GDI_BITBLT = 1,
	GDI_PATBLT,                 
	GDI_MASKBLT,
	GDI_DRAWEDGE,
	GDI_DRAWICON,
	GDI_DRAWICONEX,
	GDI_DRAWTEXT,
	GDI_DRAWFOCUSRECT,
	GDI_DPTOLP,
	GDI_ELLIPSE,				//10
	GDI_EXTTEXTOUT,
	GDI_EXCLUDECLIPRECT,
	GDI_FILLRECT,
	GDI_FILLRGN,
	GDI_INTERSECTCLIPRECT,
	GDI_GETBKCOLOR,
	GDI_GETBKMODE,
	GDI_GETCURRENTPOSITION,
	GDI_GETCLIPBOX,
	GDI_GETCLIPRGN,				//20
	GDI_GETCURRENTOBJECT,
	GDI_GETDIBITS,
	GDI_CREATEICONINDIRECT,
	GDI_DESTROYICON,
	GDI_DESTROYCURSOR,
	GDI_GETICONINFO,
	GDI_GETOBJECTTYPE,
	GDI_GETOBJECTINFO,
	GDI_GETPIXEL,
	GDI_GETROP2,				//30
	GDI_GETTEXTCOLOR,
	GDI_GETTEXTALIGN,
	GDI_GETTEXTEXTENTPOINT32,
	GDI_GETTEXTEXTENTEXPOINT,
	GDI_GETVIEWPORTORG,
	GDI_GETWINDOWORG,
	GDI_INVERTRECT,
	GDI_INVERTRGN,
	GDI_LINETO,
	GDI_LINE,					//40
	GDI_LPTODP,
	GDI_MOVETO,
	GDI_OFFSETCLIPRGN,
	GDI_OFFSETVIEWPORTORG,
	GDI_OFFSETWINDOWORG,
	GDI_POLYLINE,
	GDI_PTVISIBLE,
	GDI_RECTANGLE,
	GDI_ROUNDRECT,
	GDI_RECTVISIBLE,			//50
	GDI_SELECTOBJECT,
	GDI_DELETEOBJECT,
	GDI_DELETEDC,
	GDI_SELECTCLIPRGN,
    GDI_EXTSELECTCLIPRGN,
	GDI_SETBKCOLOR,
	GDI_SETBKMODE,
	GDI_SETBRUSHORG,
	GDI_SETMAPMODE,
	GDI_SETPIXEL,				//60
    GDI_SETROP2,
	GDI_SETTEXTCOLOR,
	GDI_SETTEXTALIGN,
	GDI_SETVIEWPORTORG,
	GDI_SETWINDOWORG,
	GDI_TEXTOUT,
	GDI_CREATEPENINDIRECT,
	GDI_CREATEPEN,
	GDI_CREATEBRUSHINDIRECT,
	GDI_CREATEHATCHBRUSH,		//70
	GDI_CREATESOLIDBRUSH,
	GDI_CREATEBITMAP,
	GDI_CREATECOMPATIBLEBITMAP,
	GDI_CREATEBITMAPINDIRECT,
	GDI_CREATECOMPATIBLEDC,
	GDI_CREATEDIBSECTION,
	GDI_SETDIBITS,
	GDI_CREATEDIBITMAP,
	GDI_GETSTOCKOBJECT,
	GDI_GETTEXTMETRICS,			//80
	GDI_GETCHARWIDTH,
	GDI_LOADIMAGE,
	GDI_LOADICON,
	GDI_LOADCURSOR,

	RGN_CREATERECT,
	RGN_CREATERECTINDIRECT,//     180
	RGN_COMBINE,
	RGN_EQUAL,
	RGN_OFFSET,
	RGN_GETBOX,
	RGN_RECTINREGION,
	RGN_PTINREGION,
	RGN_SETRECT,

	GDI_ARC,
	GDI_SETDIBITSTODEVICE,
	GDI_GETMAPMODE,
	GDI_TEXTOUTW,
	GDI_GETTEXTEXTENTPOINT32W,

	GDI_CREATEFONTINDIRECT,
	GDI_TRANSPARENTBLT,
	GDI_STRETCHBLT,
	GDI_WINDOWFROMDC,
	GDI_SETDIBCOLORTABLE,
	GDI_GETDEVICECAPS,
	GDI_ALPHABLEND_EX,
	GDI_LOADSTRING
};

#ifdef __cplusplus
}
#endif  // __cplusplus

#endif  // __EUGWME_H
